# Site settings
title: Daniel Hunt
description: Particle Physics DPhil at the University of Oxford
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Daniel Hunt
user_description: Testing
user_title: Particle Physics DPhil at the University of Oxford
email: dhunt2312@aol.co.uk
# twitter_username: lorem_ipsum
# github_username:  danieljameshunt
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
