# Site settings
title: Daniel Hunt
description: Particle Physics DPhil at the University of Oxford
# baseurl: "/home" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Daniel Hunt
user_description: Hi! I'm Dan, a physics student at Oxford. My work focuses on LZ, an experiment in South Dakota dedicated to finding non model specific mass constraints for WIMPs, a leading candidate for dark matter, though I've worked on other physics experiments too. If you want to know what that means, throw me an email. I also love outreach, and would be happy to help educate in any way I can.
user_title: Particle Physics DPhil at the University of Oxford
email: dhunt2312@aol.co.uk
# twitter_username: coming soon
# github_username:  danieljameshunt
# gplus_username:  coming soon

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
